"""add_phase_column_to_scans

Revision ID: 239776b5294d
Revises: a3c1d8e2f901
Create Date: 2026-02-19 01:15:20.358436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239776b5294d'
down_revision: Union[str, Sequence[str], None] = 'a3c1d8e2f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'phase')
    # ### end Alembic commands ###
