"""add_task_status_to_subdomain

Revision ID: d5574b00f2f8
Revises: 239776b5294d
Create Date: 2026-02-19 05:18:16.288518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5574b00f2f8'
down_revision: Union[str, Sequence[str], None] = '239776b5294d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomains', sa.Column('task_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdomains', 'task_status')
    # ### end Alembic commands ###
